[Chore] Replace cross_file with flutter_dotenv
nimblehq/flutter_mqtt_showcase pull request #12
Opened 2023-07-28 08:19 UTC by hoangnguyen92dn

- Close #10

## What happened 👀

Provide a description of the **changes** this pull request brings to the codebase. Additionally, when the pull request is still being worked on, a checklist of the planned changes is welcome to track progress.

## Insight 📝

Describe in detail why this solution is the most appropriate, which solution you tried but did not go with, and how to test the changes. References to relevant documentation are welcome as well.

TODO: Add .env to Github Actions

## Proof Of Work 📹

Show us the implementation: screenshots, GIFs, etc.

2023-07-28 09:26 UTC, luongvo commented
@hoangnguyen92dn please try to totally remove flutter_config on both Android and iOS 🙏 

```
Launching lib/main.dart on Pixel 2 XL in debug mode...
Running Gradle task 'assembleDebug'...                          

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/luongvo/WORKS/_nimblehq/_flutter/flutter_mqtt_showcase/android/app/build.gradle' line: 32

* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':flutter_config' could not be found in project ':app'.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Running Gradle task 'assembleDebug'...                             18.9s
```

2023-07-31 03:45 UTC, luongvo requested changes

2023-07-31 03:45 UTC, luongvo commented on pubspec.yaml
> +  hive_flutter: ^1.1.0
Why do we need to use hive? Wrong cherry-picking, right?

2023-07-31 07:15 UTC, hoangnguyen92dn commented on pubspec.yaml
> +  hive_flutter: ^1.1.0
Hmm...The dual display team doesn't use hive and they disabled the dependencies 😮‍💨

2023-07-31 07:58 UTC, luongvo commented on pubspec.lock
> +    version: "1.1.0"
please refresh .lock file

2023-07-31 08:14 UTC, luongvo approved these changes

2023-07-31 08:14 UTC, merged